### ISSUE TITLE
libtofi_compute.so is missing 

### ISSUE THREAD

**Issue by PrismLabs-Graz** [analogdevicesinc/ToF#103]
While building the SDK  on Linux machine I received the following error: 

[  3%] Built target ccb
make[2]: *** No rule to make target '../../libs/libtofi_compute.so', needed by 'sdk/libaditof.so.2.1.0'.  Stop.
CMakeFiles/Makefile2:105: recipe for target 'sdk/CMakeFiles/aditof.dir/all' failed
make[1]: *** [sdk/CMakeFiles/aditof.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

It was the same case that the depth compute DLL's are missing with Windows OS too. 

I think I am having the distribution package at the moment, Is there a way to get the development package including all the dependent libraries 

Thanks for your help!

**Comment by dNechita** [comment]
Hi,
Yes, the distribution package is available. Please check this release: https://github.com/analogdevicesinc/ToF/releases/tag/v2.1.1
Run the installer: TOF_Evaluation_ADTF3175-Rel2.1.1_EVAL.exe. Once things are installer, go to C:\Analog Devices\TOF_Evaluation_ADTF3175-Rel2.1.1\depth_compute_installer. Then run the installer at this path.
