### ISSUE TITLE
fsf_python.cp39-win_amd64.pyd  problem

### ISSUE THREAD

**Issue by bitslip6** [analogdevicesinc/ToF#114]
Hi.  I'm trying to parse some saved fsf files using the python scripts fsf_tools.py and fsf_python.cp39-win_amd64.pyd

I'm using python 3.9 on Windows

Everything parses correctly but it produces images similar to this.   Is it possible to access the fsf parser source file?  This might help me diagnose the issue.  I can send the fsf file over dropbox if you are interested.

Thanks much!
![frame_0_depth_z](https://user-images.githubusercontent.com/48876385/180049659-c29bf951-1ea2-445a-9d6d-e7e882e8d250.png)

**Comment by bhatiah** [comment]
Hello,

It looks like you are displaying the raw data output from data_collect. To look at depth data, you would have to process those frames through depth compute. 

Please take a look at the following link for steps on computing depth : 
https://wiki.analog.com/resources/eval/user-guides/eval-adsd3100-nxz/depthcompute_cli
