### ISSUE TITLE
No rule to make target '../../libs/libtofi_compute.so

### ISSUE THREAD

**Issue by wlamers** [analogdevicesinc/ToF#115]
Hi there,

libtofi seems missing for the SDK build. I'm on a Linux machine. I saw another issue mentioning to install the package installer to get the library, but that is for Windows. Where can I find the libtofi sources for Linux (have an NDA)?

**Comment by andrestraker** [comment]
Hi, due to licensing we are running late with the Linux Depth Compute libraries. We are in the process of getting support for depth compute on Linux. We will post when these libraries are available.

**Comment by andrestraker** [comment]
Linux support will be officially available the week of October 31st.

**Comment by andrestraker** [comment]
See the release https://github.com/analogdevicesinc/ToF/releases/tag/v3.2.0
