### ISSUE TITLE
Capture frames at 30FPS

### ISSUE THREAD

**Issue by anilsripadarao** [analogdevicesinc/ToF#135]
Currently we are able to capture devices only at 10FPS. We need to capture at 30FPS for our application. Is it possible to capture at 30FPS?

**Comment by andrestraker** [comment]
Which mode are you currently using - MP or QMP?

**Comment by anilsripadarao** [comment]
Hi Andre,
This issue is fixed with the help of @dNechita . You can mark it closed. Thank you.
