### ISSUE TITLE
Time to execute requestFrame()

### ISSUE THREAD

**Issue by anilsripadarao** [analogdevicesinc/ToF#141]
When I call **requestFrame()** to read next frame it is taking around 20millisecs. This is even after spending > 100millisecs for processing the previous frame. My assumption was by the time I call **requestFrame()** 100millisecs(10FPS) would have elapsed and I would get a frame as soon as I call this function. Am I doing something wrong or the behavior is as expected.

**Comment by dNechita** [comment]
Are you experiencing this on the embedded platform (on the NXP board)? or is this happening on a PC connected to the camera via network/usb?

**Comment by anilsripadarao** [comment]
This is on the NXP board.
