### ISSUE TITLE
Build error for Linux

### ISSUE THREAD

**Issue by jonny214** [analogdevicesinc/ToF#156]
Hi,

I had build error about [linux_build_instruction](https://github.com/analogdevicesinc/ToF/blob/master/doc/itof/linux_build_instructions.md).

![Screenshot from 2022-09-29 16-48-25](https://user-images.githubusercontent.com/28104003/192972619-be8306af-5067-4759-ab8a-0ee5aae066ca.png)

Both of SDK only and with example build has same error.

Can I have your advice for fixing this issue?

Best regards,
Jun

**Comment by rbudai98** [comment]
Hi 
Please refer to: https://github.com/analogdevicesinc/ToF/issues/115
In case you wish to build the SDK without these libraries, please add the -DUSE_DEPTH_COMPUTE_STUBS=1 to the cmake list.
