### ISSUE TITLE
Could not run tof-viewer example in Linux

### ISSUE THREAD

**Issue by HAKUTA-design** [analogdevicesinc/ToF#179]
hello,  I meet some problems in running tof-viewer example in Linux.
When I run this example, tried to click "Video: Play", the App crashed and the Terminal display :
**Conn established
Segmentation fault (core dumped)**
```shell
workspace/ToF-3.2.0/build/examples/tof-viewer$ ./ADIToFGUI 
Conn established
Connection Closed
Conn established
Segmentation fault (core dumped)
```

**Comment by bhatiah** [comment]
Hello,

Please try building again following the Linux build instructions here : https://github.com/analogdevicesinc/ToF/releases/tag/v3.2.0
