### ISSUE TITLE
Wrong location of tofi_processor.obj

### ISSUE THREAD

**Issue by mariel-tinaco** [analogdevicesinc/ToF#194]
The program is trying to locate the tofi_processor.obj in the wrong path. In my case, it's looking for it in the root python path. Could this be a build problem, or caching?

What's the way to control/manually set the parent path for the tofi_processor.obj file?

Captured a snippet of the terminal when running dnn.py
![image](https://user-images.githubusercontent.com/86707994/198437045-c37fdf76-a2b9-432a-acf7-100ac0e57d58.png)

**Comment by andrestraker** [comment]
This is due to the fact that the process executing is Python. The depth compute library looks for tof_processor.obj in that path of the executing process.
