### ISSUE TITLE
Build failed on windows - ssize_t

### ISSUE THREAD

**Issue by daniyalyasin93** [analogdevicesinc/ToF#204]
The build fails on windows for target aditofpython with Microsoft Visual Studio 2019 win64.

The error is:

```
aditofpython.cpp(142,25): error C2065: 'ssize_t': undeclared identifier [D:\Work\Repos\ToF\scripts\windows\build\bindings\python\aditofpython.vcxproj]
proj]
```

The solution is to include the header BaseTsd.h. This is described here: https://github.com/ycm-core/YouCompleteMe/issues/3949#issuecomment-944786867

**Comment by dNechita** [comment]
Hi! Can you please share the Python version that you are using?

**Comment by daniyalyasin93** [comment]
Hi
I have python 3.10.1

**Comment by dNechita** [comment]
I use python 3.9. I didn't update to anything higher due to this error.
Thank you for the fix!

**Comment by daniyalyasin93** [comment]
Thank you for approving. Glad to be able to contribute
