### ISSUE TITLE
python bindings

### ISSUE THREAD

**Issue by mejusmajus** [analogdevicesinc/ToF#237]
I connected an EVAL-ADTF3175D-NXZ to a Windows PC, installed TOF_Evaluation_ADTF3175D-Rel3.2.0_EVAL package and the ADIToFGUI is correctly working.

Then I downloaded the source of the SDK version 3.2.0, configured the enviroment with all the software needed and builded the source with the Python support (Python 3.7.9 x64 installed in the system) by executing the windows installation script.

After compilation, the ADIToFGUI from the compiled SDK is correctly working, as well as the c++ examples.

I copied the aditof.dll and the aditofpython.cp37-win_amd64.pyd to the directory of the first frame python example.
Testing the example first_frame.py it reports:

Traceback (most recent call last):
  File "first_frame.py", line 32, in <module>
    import aditofpython as tof
ImportError: DLL load failed: The specified module could not be found.

I also tried to install the python package by the setup.py with pip, but the same error occured.

Does anyone know a solution?

**Comment by dNechita** [comment]
Hi! I apologize for the huge delay.
Please check the latest master, as we've done some extra build steps to ensure everything is copied next to the python script so that is runs ok.
In case you are still facing issues, please let us know.
