### ISSUE TITLE
EVAL-ADTF3175D-NXZ exposure time adjustment

### ISSUE THREAD

**Issue by geimel** [analogdevicesinc/ToF#286]
Hello,
I would like to ask if it is possible to change the exposure setting of the sensor. I have some inexplicable noise is the depth image and will find the cause.

**Comment by bhatiah** [comment]
HI Geimel, it is not possible to change the exposure time. Are you using the 4.1.1 release with 4.1.5 firmware? If so please take a look at this page : https://wiki.analog.com/resources/eval/user-guides/eval-adtf3175d-nxz/depthcompute_params

The depth compute parameters should allow you to tweak the performance of the module. That page is updated with our recommended settings.
