### ISSUE TITLE
Missing pre-built libraries for aarch64 (NVIDIA AGX Orin)

### ISSUE THREAD

**Issue by meetgandhi-eic** [analogdevicesinc/ToF#313]
Hi,

I'm trying to interface EVAL-ADTF3175D-NXZ with Nvidia AGX Orin with Ubuntu-22.04 docker.
As mentioned in [build instructions](https://github.com/analogdevicesinc/ToF/blob/master/doc/itof/linux_build_instructions.md#linux-build-instructions) we require pre-build libraries (present in libs folder).

I'm not able to find the same for aarch64 (arm64). Can you please provide the reference from where I can get them?

**Comment by andrestraker** [comment]
Hi,

The libraries are available via the evaluation software.  If you install the latest eval kit release (4.2.0 - https://github.com/analogdevicesinc/ToF/releases/tag/v4.2.0) you can get the libraries via the highlighted installer shown in the image below.

![image](https://github.com/analogdevicesinc/ToF/assets/42846714/686ccdc0-65df-4ea9-a077-883b2560c93b)
