### ISSUE TITLE
Error fetching frames from ADTF3175NXZ on Linux PC

### ISSUE THREAD

**Issue by ssingh0017** [analogdevicesinc/ToF#365]
I have the ADTF3175NXZ, this does not have the ADSD3500. I am using a linux PC. I have built the SDK with examples from this branch https://github.com/analogdevicesinc/ToF/tree/v2.1.1 using the instructions given for linux. I see below error when running the example application for data_collect. I have tried building the SDK on my windows machine and running data_collect, here it works as expected. I believe the issue maybe due to certain dependencies not satisfied in the Linux PC. Kindly help me understand the error I see, is there any particular dependency that is needed to use the ADTF3175NXZ on a linux machine?

./data_collect --f . --n 10 --ccb test.ccb config/config_default.json 
I0705 14:18:39.693723 49263 main.cpp:372] Output folder: .
I0705 14:18:39.750444 49263 main.cpp:373] Mode: 10
I0705 14:18:39.750458 49263 main.cpp:374] Number of frames: 10
I0705 14:18:39.750463 49263 main.cpp:375] Json file: config/config_default.json
I0705 14:18:39.750466 49263 main.cpp:376] Frame type is: raw
I0705 14:18:39.750470 49263 main.cpp:377] Warm Up Time is: 0 seconds
I0705 14:18:39.750473 49263 main.cpp:384] Path to store CCB content: test.ccb
I0705 14:18:39.750479 49263 system_impl.cpp:73] SDK version: 2.1.0 | branch:  | commit: 
I0705 14:18:39.750530 49263 usb_sensor_enumerator.cpp:56] Looking for USB connected sensors
I0705 14:18:39.846940 49263 usb_sensor_enumerator.cpp:144] Found USB capture device at: /dev/video0
I0705 14:18:39.850698 49263 usb_sensor_enumerator.cpp:177] Received the following message with available sensors from target: sensors_info {
  storages {
    name: "MX25U6435F"
  }
}
I0705 14:18:39.852003 49263 camera_itof.cpp:116] Initializing camera
I0705 14:18:39.852012 49263 usb_depth_sensor_linux.cpp:114] Opening device
I0705 14:18:39.862829 49263 camera_itof.cpp:142] Current sensor firmware is: ./config/camera_configuration_walden.cfg
I0705 14:18:39.862839 49263 camera_itof.cpp:155] Current calibration file is: ./config/camera_calibration.ccb
I0705 14:18:39.862844 49263 camera_itof.cpp:173] Current Depth ini file is: ./config/RawToDepth.ini
I0705 14:18:39.875926 49263 camera_itof.cpp:219] Camera initialized
I0705 14:18:39.879431 49263 module_memory.cpp:54] Reading chunk id: ad3d
I0705 14:18:39.879443 49263 module_memory.cpp:55] Reading chunk revision: 1.0
I0705 14:18:39.882889 49263 module_memory.cpp:54] Reading chunk id: ad1
I0705 14:18:39.882900 49263 module_memory.cpp:55] Reading chunk revision: 1.0
I0705 14:18:45.158811 49263 module_memory.cpp:331] Found module memory CCB chunk, parsing...
I0705 14:18:45.158835 49263 module_memory.cpp:191] CCB file version: 303
I0705 14:18:45.158843 49263 module_memory.cpp:192] CCB calibration version: 301
I0705 14:18:45.158847 49263 module_memory.cpp:199] CCB file date: 2022--
I0705 14:18:45.158851 49263 module_memory.cpp:201] CCB chip ID: 5931
I0705 14:18:45.158855 49263 module_memory.cpp:202] CCB serial number: 00.11\d\ADI\Crosby_Output\159\  5072992.1_2_40_17               
I0705 14:18:45.158957 49263 module_memory.cpp:137] Writing temporary ccb file : /tmp/adi_tof_ccb.Rih3ad
I0705 14:18:45.163153 49263 module_memory.cpp:54] Reading chunk id: ad2
I0705 14:18:45.163164 49263 module_memory.cpp:55] Reading chunk revision: 1.0
I0705 14:18:46.930333 49263 module_memory.cpp:338] Found module memory CFG chunk, parsing...
I0705 14:18:46.930357 49263 module_memory.cpp:221] CFG file version: 1
I0705 14:18:46.930361 49263 module_memory.cpp:222] CFG configuration version: 1000.0
I0705 14:18:46.930364 49263 module_memory.cpp:223] CFG chip ID: 5931
I0705 14:18:46.930368 49263 module_memory.cpp:224] CFG system ID: 0
I0705 14:18:46.948560 49263 module_memory.cpp:137] Writing temporary cfg file : /tmp/adi_tof_cfg.dZ2cmf
I0705 14:18:46.948789 49263 module_memory.cpp:119] Writing temporary JSON file: /tmp/adi_tof_cfgjson.CO2kAe
{
"sensorFirmware": "/tmp/adi_tof_cfg.dZ2cmf",
"CCB_Calibration": "/tmp/adi_tof_ccb.Rih3ad"
}
I0705 14:18:46.948886 49263 camera_itof.cpp:116] Initializing camera
W0705 14:18:46.948918 49263 camera_itof.cpp:145] Duplicate firmware file ignored: /tmp/adi_tof_cfg.dZ2cmf
W0705 14:18:46.948995 49263 camera_itof.cpp:158] Duplicate calibration file ignored: /tmp/adi_tof_ccb.Rih3ad
I0705 14:18:46.949010 49263 camera_itof.cpp:173] Current Depth ini file is: ./config/RawToDepth.ini
I0705 14:18:46.963374 49263 camera_itof.cpp:219] Camera initialized
I0705 14:18:46.963426 49263 camera_itof.cpp:278] Chosen mode: mp
I0705 14:18:49.529914 49263 usb_depth_sensor_linux.cpp:185] Starting device
W0705 14:18:59.829526 49263 usb_depth_sensor_linux.cpp:189] VIDIOC_STREAMON, error:110(Connection timed out)
E0705 14:18:59.829566 49263 camera_itof.cpp:265] Error starting image sensor.
E0705 14:18:59.829707 49263 main.cpp:544] Could not start camera!
W0705 14:19:04.949548 49263 usb_linux_utils.cpp:304] Failed to write the length of the request string. Error: -1(Unknown error -1)
E0705 14:19:04.949621 49263 usb_storage_linux.cpp:271] Request close flash storage failed

**Comment by SeptimiuVana** [comment]
Continued the discussion on:
https://ez.analog.com/depth-perception-ranging-technologies/continuous-wave-cmos-time-of-flight-tof/f/q-a/571363/error-while-fetching-frames-from-adtf3175nxz-camera-using-a-linux-pc-sdk-built-from-this-branch-https-github-com-analogdevicesinc-tof-tree-v2-1-1
