### ISSUE TITLE
can't using ToF camera in Ubuntu

### ISSUE THREAD

**Issue by dorhalperinM** [analogdevicesinc/ToF#630]
I tried to use the ToF camera onmy ubuntu machine.
I can't open the camera at all .
Getting "Segmentation fault (core dumped)".
also cant find the ./aditof-server file

**Comment by SeptimiuVana** [comment]
Hello, can you please give us a couple of details?

What sdk version are you using?
And also can you attach the entire log from the application that you are trying to run? 

The aditof-server runs on nxp. 

Regards,
Septimiu.

**Comment by andrestraker** [comment]
Resolved via email.
